export { default as LandingPage } from './LandingPage'
export { default as Banner } from './Banner'
export { default as AboutUs } from './AboutUs'
export { default as Services } from './Services'
export { default as ServiceCard } from './ServiceCard'
export { default as ContactUs } from './ContactUs'
export { default as ContactForm } from './ContactForm'